# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Go@0
      inputs:
        command: 'test'
    - task: Docker@2
      inputs:
        containerRegistry: 'jfrog'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        method: 'PUT'
        headers: |
          {
            "Content-Type":"application/json"
          }
        body: |
          {
            "service": "$(System.TeamProject)",
            "environment": "stage",
            "tag": "$(tag)",
            "token": "$SLACK_TOKEN"
          }
        urlSuffix: 'https://r2d2.split-stage.io/deployment'
        waitForCompletion: 'false'