# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  test:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout
      - go/test
  build:
    machine: true
    steps:
      - checkout
      - run: docker build .
  deploy:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u $ARTIFACTORY_DOCKER_USER -p $ARTIFACTORY_DOCKER_PASS
          docker build .
          docker push splitio-docker.jfrog.io/$CIRCLE_PROJECT_USERNAME:$CIRCLE_SHA1
  deploy-R2D2:
    machine: true
    steps:
      run: |
        curl --header "Content-Type: application/json" \
          --request PUT \
          --data '{	"service": "$CIRCLE_PROJECT_USERNAME", "environment": "stage", "tag": "$CIRCLE_SHA1", "token": "$SLACK_TOKEN"}' \
          https://r2d2.split-stage.io/deployment


orbs:
  go: circleci/go@1.5.0

workflows:
  version: 2
  test-job-one:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
