# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout
      - go/test
  build-and-push:
    executor: docker/docker
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: cirlceci/build-test
      - docker/push:
          image: cirlceci/build-test
orbs:
  go: circleci/go@1.5.0
  docker: circleci/docker@x.y.z

workflows:
  test-job-one:
    jobs:
      - build
      - build-and-push
