# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  go: circleci/go@1.5.0
  docker: circleci/docker@1.5.0

jobs:
  test:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout
      - go/test
  build:
    machine: true
    steps:
      - checkout
      - docker/build:
          image: splitio-docker.jfrog.io/${CIRCLE_PROJECT_REPONAME}
  deploy:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-password: ARTIFACTORY_DOCKER_PASS
          docker-username: ARTIFACTORY_DOCKER_USER
          registry: splitio-docker.jfrog.io
      - docker/push:
          image: ${CIRCLE_PROJECT_REPONAME}
  deploy-R2D2:
    machine: true
    steps:
      - run: |
          curl --header 'Content-Type: application/json' --request PUT --data '{ "service": "$CIRCLE_PROJECT_REPONAME", "environment": "stage", "tag": "$CIRCLE_SHA1", "token": "$SLACK_TOKEN"}' https://r2d2.split-stage.io/deployment

workflows:
  version: 2
  test-job-one:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          context:
            - Org
          requires:
            - test
      - deploy-R2D2:
          requires:
            - deploy
