# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  go: circleci/go@1.5.0

jobs:
  test:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout
      - go/test
  build:
    machine: true
    steps:
      - checkout
      - run: docker build .
  deploy:
    machine: true
    steps:
      - checkout
      - run: |
          echo "$ARTIFACTORY_DOCKER_PASS" | docker login --username $ARTIFACTORY_DOCKER_USER --password-stdin splitio-docker.jfrog.io
          docker build -t splitio-docker.jfrog.io/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
          docker push splitio-docker.jfrog.io/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
  deploy-R2D2:
    machine: true
    steps:
      - run:
        name: Deploying to R2D2
        command: >-
        curl --header 'Content-Type: application/json'
          --request PUT
          --data '{  "service": "$CIRCLE_PROJECT_REPONAME", "environment": "stage", "tag": "$CIRCLE_SHA1", "token": "$SLACK_TOKEN"}'
          --url https://r2d2.split-stage.io/deployment

workflows:
  version: 2
  test-job-one:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          context:
            - Org
          requires:
            - test
      - deploy-r2d2:
          requires:
            - deploy
