# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  test:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout
      - go/test
  build:
    machine: true
    steps:
      - checkout
      - run: docker build .
  deploy:
    executor: docker/docker
    steps:
      - checkout
      - docker/publish:
          registry: splitio-docker.jfrog.io
          docker-username: ARTIFACTORY_DOCKER_USER
          docker-password: ARTIFACTORY_DOCKER_PASS
          image: splitio-docker.jfrog.io/$CIRCLE_PROJECT_USERNAME:$CIRCLE_SHA1

orbs:
  go: circleci/go@1.5.0
  docker: circleci/docker@1.5.0

workflows:
  version: 2
  test-job-one:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          context:
            - Org
          requires:
            - test
