# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      run: docker build
      run: docker push

workflows:
  ci:
    jobs:
      - build
